#!/usr/bin/env python2
# -*- coding: utf-8 -*-
# Extract words and their corresponding events
# Usage: ./extract_word_events.py inscript_with_events.txt

import sys
import json
import re
from collections import defaultdict as dd


FUNCTION_WORDS = {
    'a',
    'away',
    'backward',
    'backwards',
    'be',
    'because',
    'before',
    'behind',
    'below',
    'beneath',
    'beside',
    'between',
    'both',
    'but',
    'by',
    'can',
    'cannot',
    "can't",
    'cause',
    "'cos",
    'could',
    "couldn't",
    "'d",
    'despite',
    'did',
    "didn't",
    'do',
    'does',
    "doesn't",
    "don't",
    'down',
    'during',
    'each',
    'either',
    'even',
    'ever',
    'every',
    'except',
    'for',
    'had',
    "hadn't",
    'has',
    "hasn't",
    'have',
    'how',
    'however',
    'i',
    'if',
    'in',
    'inside',
    'inspite',
    'instead',
    'into',
    'is',
    "isn't",
    'it',
    'its',
    'itself',
    'just',
    "'ll",
    'least',
    'less',
    'like',
    "'m",
    'many',
    'may',
    "mayn't",
    'me',
    'might',
    "mightn't",
    'mine',
    'more',
    'most',
    'much',
    'must',
    "mustn't",
    'my',
    'myself',
    'near',
    'need',
    "needn't",
    'needs',
    'neither',
    'never',
    'no',
    'none',
    'nor',
    'not',
    'now',
    'of',
    'off',
    'often',
    'on',
    'once',
    'only',
    'onto',
    'or',
    'ought',
    "oughtn't",
    'our',
    'ours',
    'ourselves',
    'out',
    'outside',
    'over',
    'past',
    'perhaps',
    'quite',
    "'re",
    'rather',
    "'s",
    'seldom',
    'several',
    'shall',
    "shan't",
    'she',
    'should',
    "shouldn't",
    'since',
    'so',
    'some',
    'sometimes',
    'soon',
    'than',
    'that',
    'the',
    'together',
    'too',
    'towards',
    'under',
    'unless',
    'until',
    'up',
    'upon',
    'us',
    'used',
    "usedn't",
    "usen't",
    'usually',
    "'ve",
    'very',
    'was',
    "wasn't",
    'we',
    'well',
    'were',
    "weren't",
    'what',
    'when',
    'where',
    'whether',
    'which',
    'while',
    'who',
    'whom',
    'whose',
    'why',
    'will',
    'with',
    'without',
    "won't",
    'would',
    "wouldn't",
    'yet',
    'you',
    'your',
    'yours',
    'yourself',
    'yourselves'
    }


rx = re.compile(r'\w+_\(\w+\)')

with open(sys.argv[1], 'r') as fopen:
    fdata = fopen.read()


word_events = dd(list)
for pair in rx.findall(fdata):
    word, bevent = pair.split('_', 1)
    if word.lower() not in FUNCTION_WORDS:
        event = re.sub(r'[\(\)]', '', bevent)
        #print '{0:<15} {1}'.format(word, event)
        word_events[word].append(event)


with open("word_events.json", "w") as jsonfile:
    json.dump(word_events, jsonfile, indent=2, separators=(',', ': '))

print('word_events.json was generated')

